apiVersion: v2
name: sonarqube
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.16.0"

dependencies:
  - condition: postgresql.enabled
    name: postgresql
    version: "12.12.10"
    repository: https://charts.bitnami.com/bitnami
